# Generated by Django 6.0.3 on 2026-04-08 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='output',
            field=models.ImageField(blank=True, null=True, upload_to='task_outputs/'),
        ),
        migrations.AddField(
            model_name='task',
            name='story',
            field=models.TextField(blank=True),
        ),
    ]
