# Generated by Django 6.0.3 on 2026-04-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_assigned_by_task_output_task_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
