# Generated by Django 6.0.2 on 2026-04-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('improve', 'Should Improve')], default='pending', max_length=20),
        ),
    ]
